sudo: required
language: node_js
node_js: "7"
services:
  - docker
env: 
  - AUTH=false
  - AUTH=true USER=test PASSWORD=secret
# Install dependencies for the testing environment
install: npm install
# Build and start the container
before_script: 
  - docker build -t testshortener .
  - docker run -d -p 3000:3000 -e AUTH=$AUTH -e USER=$USER -e PASSWORD=$PASSWORD --name testcon1 testshortener
script:
  - npm run lint
  - npm test
branches:
  only:
    - master
notifications:
  email:
    - dennis.wolters@uni-paderborn.de
